name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test-deploy:
    name: Test and deploy
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go: [1.17]
        os: [windows-latest]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}

      - name: Build for Windows
        if: startsWith(matrix.os, 'windows-')
        run: |
          $GIT_COMMIT = (git describe --always --dirty) | Out-String
          $DATE_TIME = ([datetime]::Now.ToUniversalTime().toString("yyyy-MM-ddTHH:mm:ssZ")) | Out-String
          go build -trimpath -ldflags "-s -w -X github.com/drakkan/sftpgo/v2/version.commit=$GIT_COMMIT -X github.com/drakkan/sftpgo/v2/version.date=$DATE_TIME" -o sftpgo.exe
          .\sftpgo.exe initprovider

      - name: Prepare Windows installer
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        run: |
          mkdir output
          copy .\sftpgo.exe .\output
          copy .\sftpgo.json .\output
          copy .\sftpgo.db .\output
          copy .\LICENSE .\output\LICENSE.txt
          mkdir output\templates
          xcopy .\templates .\output\templates\ /E
          mkdir output\static
          xcopy .\static .\output\static\ /E
          $Env:SFTPGO_ISS_DEV_VERSION = "2.1.2.105"
          $CERT_PATH=(Get-Location -PSProvider FileSystem).ProviderPath + "\cert.pfx"
          echo "writing cert"
          [IO.File]::WriteAllBytes($CERT_PATH,[System.Convert]::FromBase64String("${{ secrets.CERT_DATA }}"))
          Get-FileHash $CERT_PATH
          echo "importing cert"
          certutil -f -p ${{ secrets.CERT_PASS }} -importpfx "$CERT_PATH"
          echo "rmeoving cert"
          rm "$CERT_PATH"
          $INNO_S='/Ssigntool=$qC:/Program Files (x86)/Windows Kits/10/bin/10.0.17763.0/x86/signtool.exe$q sign /sm /tr http://timestamp.sectigo.com /td sha256 /fd sha256 /n $qNicola Murino$q /d $qSFTPGo$q $f'
          echo "inno_s $INNO_S"
          iscc "$INNO_S" windows-installer\sftpgo.iss
          echo "remove cert"
          certutil -delstore "Nicola Murino"
        env:
          CERT_DATA: ${{ secrets.CERT_DATA }}
          CERT_PASS: ${{ secrets.CERT_PASS }}

      - name: Upload Windows installer artifact
        if: ${{ startsWith(matrix.os, 'windows-') && github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v2
        with:
          name: sftpgo_windows_installer_x86_64
          path: ./sftpgo_windows_x86_64.exe